{{- if .Values.crds.install }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalsources.source.flux.oddkin.co
  labels:
    {{- include "flux-external-controller.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.crds.keep }}
    "helm.sh/resource-policy": keep
    {{- end }}
spec:
  group: source.flux.oddkin.co
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required: [interval, generator]
            properties:
              interval:
                type: string
                pattern: '^([0-9]+(\.[0-9]+)?(ms|s|m|h))+$'
              suspend:
                type: boolean
              destinationPath:
                type: string
              transform:
                type: object
                properties:
                  type:
                    type: string
                    enum: [cel]
                  expression:
                    type: string
              generator:
                type: object
                required: [type]
                properties:
                  type:
                    type: string
                    enum: [http]
                  http:
                    type: object
                    required: [url]
                    properties:
                      url:
                        type: string
                        format: uri
                      method:
                        type: string
                        default: GET
                      headersSecretRef:
                        type: object
                        properties:
                          name:
                            type: string
                      caBundleSecretRef:
                        type: object
                        properties:
                          name:
                            type: string
                          key:
                            type: string
                      insecureSkipVerify:
                        type: boolean
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
              artifact:
                type: object
                properties:
                  url:
                    type: string
                  revision:
                    type: string
                  lastUpdateTime:
                    type: string
                    format: date-time
              lastHandledETag:
                type: string
              observedGeneration:
                type: integer
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: externalsources
    singular: externalsource
    kind: ExternalSource

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalartifacts.source.flux.oddkin.co
  labels:
    {{- include "flux-external-controller.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.crds.keep }}
    "helm.sh/resource-policy": keep
    {{- end }}
spec:
  group: source.flux.oddkin.co
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required: [url, revision]
            properties:
              url:
                type: string
                format: uri
              revision:
                type: string
              metadata:
                type: object
                additionalProperties:
                  type: string
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
              observedGeneration:
                type: integer
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: externalartifacts
    singular: externalartifact
    kind: ExternalArtifact
{{- end }}