run:
  timeout: 5m
  allow-parallel-runners: true
  skip-dirs:
    - third_party
    - builtin
    - examples

linters:
  disable-all: true
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused

issues:
  exclude-rules:
    - path: api/
      linters:
        - lll
    - path: internal/
      linters:
        - dupl
        - lll
