# golangci-lint v2.x configuration
version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - dupl
    - goconst
    - gocyclo
    - misspell
    - unconvert
    - unparam
    - prealloc
    - nakedret
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: api/
        text: "Line too long"
      - path: internal/
        text: "duplicate"
