# This rule is not used by the project flux-externalsource-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to source.flux.oddkin.co resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: flux-externalsource-controller
    app.kubernetes.io/managed-by: kustomize
  name: externalsource-viewer-role
rules:
- apiGroups:
  - source.flux.oddkin.co
  resources:
  - externalsources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.flux.oddkin.co
  resources:
  - externalsources/status
  verbs:
  - get
