# This rule is not used by the project flux-externalsource-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over source.flux.oddkin.co.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: flux-externalsource-controller
    app.kubernetes.io/managed-by: kustomize
  name: externalsource-admin-role
rules:
- apiGroups:
  - source.flux.oddkin.co
  resources:
  - externalsources
  verbs:
  - '*'
- apiGroups:
  - source.flux.oddkin.co
  resources:
  - externalsources/status
  verbs:
  - get
