# This rule is not used by the project flux-externalsource-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the source.flux.oddkin.co.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: flux-externalsource-controller
    app.kubernetes.io/managed-by: kustomize
  name: externalsource-editor-role
rules:
- apiGroups:
  - source.flux.oddkin.co
  resources:
  - externalsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - source.flux.oddkin.co
  resources:
  - externalsources/status
  verbs:
  - get
