apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: flux-externalsource-controller
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
