apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: externalsource-controller-system

resources:
- ../default

patchesStrategicMerge:
- manager-development-patch.yaml

images:
- name: controller
  newName: externalsource-controller
  newTag: dev