apiVersion: source.flux.oddkin.co/v1alpha1
kind: ExternalSource
metadata:
  labels:
    app.kubernetes.io/name: flux-externalsource-controller
    app.kubernetes.io/managed-by: kustomize
  name: externalsource-sample
spec:
  interval: 5m
  destinationPath: config.json
  generator:
    type: http
    http:
      url: https://api.example.com/config
      method: GET
  transform:
    type: cel
    expression: 'has(data.config) ? data.config : data'
