apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: externalsource-controller-system

resources:
- ../default

patchesStrategicMerge:
- manager-production-patch.yaml

replacements:
- source:
    kind: ConfigMap
    name: externalsource-controller-config
    fieldPath: data
  targets:
  - select:
      kind: Deployment
      name: controller-manager
    fieldPaths:
    - spec.template.spec.containers.[name=manager].env.[name=CONFIG_MAP_NAME].value

images:
- name: controller
  newName: externalsource-controller
  newTag: latest