apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller-manager
  namespace: externalsource-controller-system
spec:
  replicas: 2  # High availability
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: control-plane
                  operator: In
                  values:
                  - controller-manager
              topologyKey: kubernetes.io/hostname
      containers:
      - name: manager
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        env:
        - name: STORAGE_BACKEND
          value: "s3"
        - name: METRICS_ENABLED
          value: "true"
        - name: HTTP_TIMEOUT
          value: "60s"
        - name: RETRY_MAX_ATTEMPTS
          value: "15"
        - name: TRANSFORM_TIMEOUT
          value: "60s"