{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fx-controller.metricsServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fx-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
  - name: metrics
    port: {{ .Values.metrics.service.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "fx-controller.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: manager
{{- end }}

{{- if .Values.webhook.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fx-controller.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fx-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  type: ClusterIP
  ports:
  - name: webhook-server
    port: 443
    protocol: TCP
    targetPort: {{ .Values.webhook.port }}
  selector:
    {{- include "fx-controller.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: manager
{{- end }}