name: Helm Chart Release

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  release-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}



    - name: Check for chart changes
      id: changes
      run: |
        if git diff --name-only HEAD~1 HEAD | grep -q "charts/"; then
          echo "charts-changed=true" >> $GITHUB_OUTPUT
        else
          echo "charts-changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Bump chart version
      id: bump-version
      if: steps.changes.outputs.charts-changed == 'true'
      run: |
        # Get current version
        CURRENT_VERSION=$(grep '^version:' charts/flux-externalsource-controller/Chart.yaml | awk '{print $2}')
        
        # Increment patch version
        NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
        
        # Update Chart.yaml
        sed -i "s/version: $CURRENT_VERSION/version: $NEW_VERSION/" charts/flux-externalsource-controller/Chart.yaml
        
        echo "Updated chart version from $CURRENT_VERSION to $NEW_VERSION"
        echo "new-version=$NEW_VERSION" >> $GITHUB_OUTPUT

    - name: Package and release chart
      if: steps.changes.outputs.charts-changed == 'true'
      run: |
        # Package chart
        helm package charts/flux-externalsource-controller
        
        # Push to OCI registry
        helm push flux-externalsource-controller-*.tgz oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts
        
        echo "Chart pushed to oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts"

    - name: Create GitHub release
      if: steps.changes.outputs.charts-changed == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: helm-chart-v${{ steps.bump-version.outputs.new-version }}
        name: Helm Chart v${{ steps.bump-version.outputs.new-version }}
        body: |
          ## Helm Chart Release v${{ steps.bump-version.outputs.new-version }}
          
          ### Installation
          ```bash
          helm install flux-externalsource-controller oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts/flux-externalsource-controller --version ${{ steps.bump-version.outputs.new-version }}
          ```
        files: flux-externalsource-controller-*.tgz

    - name: Commit version bump
      if: steps.changes.outputs.charts-changed == 'true'
      run: |
        git add charts/flux-externalsource-controller/Chart.yaml
        git commit -m "chore: bump chart version" || exit 0
        git push